=head1 NAME

Test::HTTP::VCR - A recorder for HTTP requests

=head1 VERSION

Version 0.01

=head1 SYNOPSIS

    use Test::HTTP::VCR;
    use Furl;

    my $httpclient = Furl->new;
    my $filename = 'mytape.tape';
    my $vcr = Test::HTTP::VCR->new($filename);
    my $response;
    $vcr->record(sub {
        $response = $httpclient->get('https://www.github.com');
    });
    
    # $another_response should be the same as $response;
    $vcr->play(sub {
        my $another_response = $httpclient->get('https://www.github.com');
    });

=head1 DESCRIPTION

A tool to record and playback your HTTP interactions. This is especially useful for
testing web APIs.

Inspired by the Ruby library, VCR (https://github.com/vcr/vcr)

NOTE: This is alpha-level software.

=head1 SUBROUTINES/METHODS

=head2 new

=head2 record

=head2 play


=head1 TODO

=over 4

=item Spin up a simple HTTP server for testing

=item Test other HTTP methods (POST, PUT, DELETE)

=back

=head1 AUTHOR

skliew, C<< <skliew at gmail.com> >>

=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc Test::HTTP::VCR

=head1 LICENSE AND COPYRIGHT

Artistic License 2.0. See LICENSE for details.

